# --- FACMAC specific parameters ---
action_selector: gumbel
epsilon_start: 0.5
epsilon_finish: 0.01
epsilon_anneal_time: 5000
agent: gnn
obs_agent_id: False # Include the agent's one_hot id in the observation
obs_last_action: False # Include the agent's last action (one_hot) in the observation
agent_output_type: pi_logits
batch_size_run: 1
batch_size: 64
buffer_size: 32768
buffer_warmup: 0
discretize_actions: False
double_q: False
epsilon_decay_mode: ~
gamma: 0.0
grad_norm_clip: 1
learner: aps_learner # "facmac_learner_discrete"
lr: 0.001
critic_lr: 0.001
td_lambda: 1.0
critic_train_reps: 1
mac: basic_mac
mixer: ~
mixing_embed_dim: 32
skip_connections: False
gated: False
hypernet_layers: 2
hypernet_embed: 64
hyper_initialization_nonzeros: 0
name: facmac_aps
n_runners: ~
n_train: 1
optimizer: adam
ou_stop_episode: 100 # training noise goes to zero after this episode
rnn_hidden_dim: 64
run_mode: ~
runner: episode
runner_scope: episodic
target_update_interval: 200
target_update_mode: hard
target_update_tau: 0.001
test_greedy: False
test_interval: 10000
test_nepisode: 32
testing_on: False
t_max: 100000
save_model: False
save_model_interval: 10000
verbose: False
weight_decay: True
weight_decay_factor: 0.0001
agent_return_logits: False
q_embed_dim: 1
mask_before_softmax: False
